GAMEPAD_ACTION_RIGHT  cycle pause ; show-text "${playback-time} / ${duration}"
GAMEPAD_LEFT_SHOULDER  seek -30 ; show-text "${playback-time} / ${duration}"
GAMEPAD_RIGHT_SHOULDER seek  30 ; show-text "${playback-time} / ${duration}"
GAMEPAD_DPAD_LEFT      seek -5 ; show-text "${playback-time} / ${duration}"
GAMEPAD_DPAD_RIGHT     seek  5 ; show-text "${playback-time} / ${duration}"
GAMEPAD_ACTION_DOWN   quit
#GAMEPAD_START          quit
GAMEPAD_MENU          script-binding stats/display-stats-toggle
