#!/usr/bin/env python3
"""Copy the minimal XKB data WPE needs into <out>: WPEKeymapXKB always compiles the keymap
rules=evdev, model=pc105, layout=us (the browser's own keyboards use the precompiled keymaps
from scripts/xkb-keymaps.py). Writes a one-line-per-component rules file for exactly that and
copies only the component files it reaches (following include/augment/override statements).
Usage: xkb-minimal.py <xkb-source-root> <out-dir>"""
import os
import re
import shutil
import sys

SRC, OUT = sys.argv[1], sys.argv[2]

# What the evdev rules resolve to for pc105 + one layout (no variant/options)
COMPONENTS = {
    "keycodes": "evdev+aliases(qwerty)",
    "types": "complete",
    "compat": "complete",
    "symbols": "pc+us+inet(evdev)",
}
RULES = """// Minimal rules (model pc105, one layout). Generated by scripts/xkb-minimal.py.
! model = keycodes
  * = evdev+aliases(qwerty)

! model = types
  * = complete

! model = compat
  * = complete

! model layout = symbols
  * * = pc+%l%(v)+inet(evdev)
"""

INCLUDE = re.compile(r'\b(?:include|augment|override|replace)\s+"([^"]+)"')


def names(spec):
    """'pc+us(intl):2|foo' -> ['pc', 'us', 'foo']"""
    return [re.sub(r"[(:].*", "", part) for part in re.split(r"[+|^]", spec) if part]


needed = set()
for kind, spec in COMPONENTS.items():
    todo = names(spec)
    while todo:
        name = todo.pop()
        path = os.path.join(kind, name)
        if path in needed:
            continue
        if not os.path.isfile(os.path.join(SRC, path)):
            sys.exit(f"missing {path}")
        needed.add(path)
        with open(os.path.join(SRC, path), encoding="utf-8", errors="replace") as f:
            for spec_inc in INCLUDE.findall(f.read()):
                todo.extend(names(spec_inc))

shutil.rmtree(OUT, ignore_errors=True)
for path in sorted(needed):
    os.makedirs(os.path.join(OUT, os.path.dirname(path)), exist_ok=True)
    shutil.copy(os.path.join(SRC, path), os.path.join(OUT, path))
os.makedirs(os.path.join(OUT, "rules"), exist_ok=True)
with open(os.path.join(OUT, "rules", "evdev"), "w") as f:
    f.write(RULES)
print(f"xkb: {len(needed)} component files + rules/evdev")
